# Generated by Django 5.0.7 on 2024-10-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Book', '0002_book_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='content',
        ),
    ]
