# Generated by Django 5.0.7 on 2024-10-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Book', '0003_remove_complaint_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
